### ISSUE TITLE
attributify mode with prefix doesn't show the info

### ISSUE THREAD

**Issue by ryoppippi** [xna00/unocss-language-server#15]
for example
```html
<div mxa />
```
shows info like this:
```css
/* layer: default */
.mxa{margin-left:auto;margin-right:auto;}
```

However, when adding prefix:
```html
<div un-mxa />
```
This does not show any information.
